import {
  User,
  UserRole,
  AuthResponse,
  Category,
  Exam,
  ExamDetail,
  Question,
  QuestionType,
  ExamDifficulty,
  ExamVisibility,
  ExamStatus,
  AttemptStatus,
  StartExamResponse,
  AttemptDetail,
  SavedAnswer,
  SubmitExamResponse,
  StudentAttempt,
  ResultDetail,
  ParticipantResult,
  StudentAnalytics,
  TeacherAnalytics,
  AdminAnalytics,
  PagedResult,
  ApiResponse,
} from '../types';

export const mockUsers: User[] = [
  {
    id: '11111111-1111-1111-1111-111111111111',
    fullName: 'Admin User',
    email: 'admin@testplatform.uz',
    role: UserRole.Admin,
    isActive: true,
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: '22222222-2222-2222-2222-222222222222',
    fullName: 'Anvar Karimov (Teacher)',
    email: 'teacher@testplatform.uz',
    role: UserRole.Teacher,
    isActive: true,
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-01-10T00:00:00Z',
  },
  {
    id: '33333333-3333-3333-3333-333333333333',
    fullName: 'Jasur Bekmurodov (Student)',
    email: 'student@testplatform.uz',
    role: UserRole.Student,
    isActive: true,
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-01-15T00:00:00Z',
  },
  {
    id: '44444444-4444-4444-4444-444444444444',
    fullName: 'Aziza Rahimova (Student)',
    email: 'aziza@testplatform.uz',
    role: UserRole.Student,
    isActive: true,
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    createdAt: '2026-01-20T00:00:00Z',
  },
];

export const mockCategories: Category[] = [
  {
    id: 'a1111111-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    nameUz: 'IT & Dasturlash',
    nameRu: 'IT и Программирование',
    nameEn: 'IT & Programming',
    slug: 'it-programming',
    descriptionUz: 'C#, .NET, JavaScript, React, Ma\'lumotlar bazasi va zamonaviy web texnologiyalari.',
    icon: 'Code2',
    color: '#3B82F6',
    displayOrder: 1,
    isActive: true,
    examCount: 2,
  },
  {
    id: 'a2222222-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    nameUz: 'Matematika & Mantiq',
    nameRu: 'Математика и Логика',
    nameEn: 'Mathematics & Logic',
    slug: 'mathematics-logic',
    descriptionUz: 'Oliy matematika, chiziqli algebra, kombinatorika va mantiqiy masalalar.',
    icon: 'Binary',
    color: '#10B981',
    displayOrder: 2,
    isActive: true,
    examCount: 0,
  },
  {
    id: 'a3333333-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    nameUz: 'Ingliz tili (IELTS / CEFR)',
    nameRu: 'Английский язык (IELTS / CEFR)',
    nameEn: 'English Language (IELTS / CEFR)',
    slug: 'english-language',
    descriptionUz: 'Grammatika, so\'z boyligi, Reading va Writing bo\'yicha maxsus testlar.',
    icon: 'Languages',
    color: '#8B5CF6',
    displayOrder: 3,
    isActive: true,
    examCount: 1,
  },
  {
    id: 'a4444444-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    nameUz: 'Fizika & Muhandislik',
    nameRu: 'Физика и Инженерия',
    nameEn: 'Physics & Engineering',
    slug: 'physics-engineering',
    descriptionUz: 'Mexanika, termodinamika, elektrodinamika va kvant fizikasi asoslari.',
    icon: 'Atom',
    color: '#F59E0B',
    displayOrder: 4,
    isActive: true,
    examCount: 0,
  },
];

export const mockExams: Exam[] = [
  {
    id: 'e1111111-1111-1111-1111-111111111111',
    title: 'C# & .NET 10 Kengaytirilgan Imtihon',
    description: 'C# 14, .NET 10, Memory management, LINQ va Entity Framework Core bo\'yicha professional bilim darajasini tekshiruvchi test.',
    categoryId: 'a1111111-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    categoryName: 'IT & Dasturlash',
    categoryColor: '#3B82F6',
    categoryIcon: 'Code2',
    teacherId: '22222222-2222-2222-2222-222222222222',
    teacherName: 'Anvar Karimov',
    difficulty: ExamDifficulty.Medium,
    durationMinutes: 30,
    passingScore: 70,
    visibility: ExamVisibility.Public,
    status: ExamStatus.Published,
    totalQuestions: 4,
    totalPoints: 40,
    maxAttempts: 3,
    participantCount: 2,
    averageScore: 75,
    createdAt: '2026-02-01T00:00:00Z',
  },
  {
    id: 'e2222222-2222-2222-2222-222222222222',
    title: 'React 19 & TypeScript Professional Test',
    description: 'Server Actions, React Hooks, useOptimistic, Type narrowings va zamonaviy frontend arxitekturasi.',
    categoryId: 'a1111111-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    categoryName: 'IT & Dasturlash',
    categoryColor: '#3B82F6',
    categoryIcon: 'Code2',
    teacherId: '22222222-2222-2222-2222-222222222222',
    teacherName: 'Anvar Karimov',
    difficulty: ExamDifficulty.Hard,
    durationMinutes: 45,
    passingScore: 75,
    visibility: ExamVisibility.Public,
    status: ExamStatus.Published,
    totalQuestions: 3,
    totalPoints: 30,
    maxAttempts: 3,
    participantCount: 1,
    averageScore: 85,
    createdAt: '2026-02-05T00:00:00Z',
  },
  {
    id: 'e3333333-3333-3333-3333-333333333333',
    title: 'IELTS Academic Reading & Grammar Test',
    description: 'Advanced academic vocabulary, complex grammatical structures, and comprehension diagnostics.',
    categoryId: 'a3333333-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
    categoryName: 'Ingliz tili (IELTS / CEFR)',
    categoryColor: '#8B5CF6',
    categoryIcon: 'Languages',
    teacherId: '22222222-2222-2222-2222-222222222222',
    teacherName: 'Anvar Karimov',
    difficulty: ExamDifficulty.Medium,
    durationMinutes: 40,
    passingScore: 65,
    visibility: ExamVisibility.Public,
    status: ExamStatus.Published,
    totalQuestions: 3,
    totalPoints: 30,
    maxAttempts: 5,
    participantCount: 1,
    averageScore: 90,
    createdAt: '2026-02-10T00:00:00Z',
  },
];

export const mockQuestions: Record<string, Question[]> = {
  'e1111111-1111-1111-1111-111111111111': [
    {
      id: 'q1',
      examId: 'e1111111-1111-1111-1111-111111111111',
      text: 'C# da `record` struct va `class` orasidagi asosiy farq nima?',
      questionType: QuestionType.SingleChoice,
      points: 10,
      order: 1,
      explanation: 'Record turi qiymat bo\'yicha tenglikni (value-based equality) avtomatik ta\'minlaydi.',
      options: [
        { id: 'o1', questionId: 'q1', text: 'Record value-based equality taqdim etadi', isCorrect: true, order: 1 },
        { id: 'o2', questionId: 'q1', text: 'Record faqat heap xotirada joylashadi', isCorrect: false, order: 2 },
        { id: 'o3', questionId: 'q1', text: 'Class da constructor yozib bo\'lmaydi', isCorrect: false, order: 3 },
        { id: 'o4', questionId: 'q1', text: 'Record larni meros qilib bo\'lmaydi', isCorrect: false, order: 4 },
      ],
    },
    {
      id: 'q2',
      examId: 'e1111111-1111-1111-1111-111111111111',
      text: 'Qaysi kalit so\'zlar C# da xotirani boshqarish va resurslarni ozod qilish uchun ishlatiladi? (Ko\'p tanlovli)',
      questionType: QuestionType.MultipleChoice,
      points: 10,
      order: 2,
      explanation: '`using` va `IDisposable` C# da unmanaged resurslarni deterministic tozalash uchun xizmat qiladi.',
      options: [
        { id: 'o5', questionId: 'q2', text: 'using block', isCorrect: true, order: 1 },
        { id: 'o6', questionId: 'q2', text: 'IDisposable interfeysi', isCorrect: true, order: 2 },
        { id: 'o7', questionId: 'q2', text: 'goto operatori', isCorrect: false, order: 3 },
        { id: 'o8', questionId: 'q2', text: 'params kalit so\'zi', isCorrect: false, order: 4 },
      ],
    },
    {
      id: 'q3',
      examId: 'e1111111-1111-1111-1111-111111111111',
      text: '.NET 10 da CancellationToken yordamida uzoq davom etuvchi async operatsiyani bekor qilish mumkin.',
      questionType: QuestionType.TrueFalse,
      points: 10,
      order: 3,
      explanation: 'Rost. CancellationToken asinxron vazifani xavfsiz to\'xtatish imkonini beradi.',
      options: [
        { id: 'o9', questionId: 'q3', text: 'Rost (True)', isCorrect: true, order: 1 },
        { id: 'o10', questionId: 'q3', text: 'Yolg\'on (False)', isCorrect: false, order: 2 },
      ],
    },
    {
      id: 'q4',
      examId: 'e1111111-1111-1111-1111-111111111111',
      text: 'Quyidagi kod natijasida konsolga nima chiqadi?',
      codeSnippet: 'int x = 5;\nConsole.WriteLine(x++ + ++x);',
      questionType: QuestionType.SingleChoice,
      points: 10,
      order: 4,
      explanation: 'x++ qiymati 5 (so\'ng x=6), keyin ++x x ni 7 ga oshiradi va 7 qaytaradi. 5 + 7 = 12.',
      options: [
        { id: 'o11', questionId: 'q4', text: '12', isCorrect: true, order: 1 },
        { id: 'o12', questionId: 'q4', text: '11', isCorrect: false, order: 2 },
        { id: 'o13', questionId: 'q4', text: '10', isCorrect: false, order: 3 },
        { id: 'o14', questionId: 'q4', text: '13', isCorrect: false, order: 4 },
      ],
    },
  ],
};
